version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - migrations/database.sql:/tmp/db.sql
    environment:
      - MYSQL_ROOT_PASSWORD:root
    ports:
      - 3306:3306